[package]
name = "hearth-tests"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]

[dev-dependencies]
holochain = { version = "0.7.0", features = ["test_utils"] }
holochain_types = "0.7.0"
holochain_zome_types = "0.7.0"
hdk = "0.7.0"
aboutme_integrity = { path = "../dnas/aboutme/zomes/integrity/aboutme" }
aboutme = { path = "../dnas/aboutme/zomes/coordinator/aboutme" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
