[package]
name = "aboutme"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "aboutme"

[dependencies]
hdk = { workspace = true }
yaml_serde = { workspace = true }
serde = { workspace = true }
aboutme_integrity = { path = "../../integrity/aboutme" }
holochain_serialized_bytes = { workspace = true }
